### ISSUE TITLE
State of charge as a value in kWh

### ISSUE THREAD

**Issue by creativethings** [PimDoos/ha-sessy#104]
Currently state of charge is only available as a percentage of the battery capacity. Please also provide a parameter for the actual value in kWh. 

As an example for how this could be done in ha config yaml:
      battery_state_of_charge_kwh:
       friendly_name: "State of Charge kWh"
       unit_of_measurement: "kWh"
       value_template: >-
          {% set c = 5 %}
          {% set s = states('sensor.sessy_****_state_of_charge') | int %}
          {% set d = s/100 * c %}
          {{ '{:.2f}'.format(d) }}

**Comment by PimDoos** [comment]
This integration provides the values as they are provided by Sessy's API. The current capacity in kWh is not provided by Sessy's API. As we don't know the actual full capacity of the battery at any point in time (due to degradation and deviation in the reported state of charge), multiplying the SOC by a fixed number will not give an entirely accurate representation.
You are, of course, free to use template sensors to estimate the energy in the battery.

**Comment by AJediIAm** [comment]
Would it be possible to add the template to the wiki or documentation? I think commonly used templates are areasonable compromis and helpful for many users.

**Comment by PimDoos** [comment]
This is a good point, I currently have https://github.com/PimDoos/ha-sessy-examples for example code, but will look into adding a wiki to this repo for common templates
