### ISSUE TITLE
Sessy state of charge % value not correct displayed in home assistant

### ISSUE THREAD

**Issue by robertjantak** [PimDoos/ha-sessy#78]
Hello, it appears that the state of charge is not correctly displayed at home assistant.

this results is viseable in home assistant, the battery status is empty but still gives a state of charge of 4.0 %

here are some logs;
this is the state of charge gathered directly from the api;

{
	"status":	"ok",
	"sessy":	{
		"state_of_charge":	0.070000000298023224,
		"power":	-2036,
		"power_setpoint":	-2200,
		"system_state":	"SYSTEM_STATE_RUNNING_SAFE",
		"system_state_details":	"",
		"frequency":	50030
	},
	"renewable_energy_phase1":	{
		"voltage_rms":	228020,
		"current_rms":	337,
		"power":	76

this is what is displayed at home assistant;
Sessy-D9C9 State of Charge
1 minuut geleden
7,0%

**Comment by PimDoos** [comment]
The state of charge is provided by the api as a unit interval float. 1 == 100%, 0 == 0%. So the value you see in HA is the value provided by Sessy.

The discrepancy you're seeing is likely due to the BMS providing a skewed state of charge. This is a known issue at Sessy.
To calibrate the state of charge, you can fully charge and then fully discharge the battery. After this, the state of charge will be much more accurate.
